apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-update
  namespace: default  # Change this to your specific namespace
spec:
  schedule: "0 */3 * * *"  # Runs every 3 hours
  jobTemplate:
    spec:
      backoffLimit: 1  # Number of retries if job fails
      template:
        spec:
          serviceAccountName: k8s-service-account
          containers:
          - name: postgres-updater
            image: mukund0004/pushpred:v6 # Replace with your image
            imagePullPolicy: Always
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                cpu: 1
                memory: 1Gi
            
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
